ARG BASE_IMAGE_TAG
FROM app.harness.io/registry/harness/delegate:${BASE_IMAGE_TAG}

LABEL maintainer="konrness@gmail.com"
LABEL source="https://github.com/konrness/harness-custom-delegate"

# See https://cloud.google.com/sdk/docs/install#rpm
USER 0

RUN echo -e "[google-cloud-cli]\n\
name=Google Cloud CLI\n\
baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64\n\
enabled=1\n\
gpgcheck=1\n\
repo_gpgcheck=0\n\
gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" | tee /etc/yum.repos.d/google-cloud-sdk.repo && \
    microdnf -y install google-cloud-cli

USER 1001
