ARG BASE_IMAGE_TAG
FROM harness/delegate:${BASE_IMAGE_TAG}
ARG TERRAFORM_VERSION="1.3.9"
LABEL TERRAFORM_VERSION=${TERRAFORM_VERSION}

LABEL maintainer="konrness@gmail.com"
LABEL source="https://github.com/konrness/harness-custom-delegate"

USER 0

RUN echo Install terraform ${TERRAFORM_VERSION} && \
    microdnf -y install git unzip && \
    microdnf clean all && \
    curl -O -L https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    mv ./terraform /usr/bin/

USER 1001

RUN  terraform --version